mgm_app/urls.py
from django.urls import path
from . import views

app_name = 'mgm_app'

urlpatterns = [
    path("", views.inicio, name="inicio"),
    path("usuarios/", views.usuarios, name="usuarios"),
    path("recetas/", views.recetas, name="recetas"),
    path("condimentos/", views.condimentos, name="condimentos"),
    path("usuarios/creacion/", views.usuario_creacion, name="usuario_creacion"),
]

mgm_proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('mgm_app.urls', 'mgm_app'), namespace='mgm_app')),
]

mgm_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Usuarios(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    

class Condimentos(models.Model):
    fracciones = [
        ('litros', 'Litros'),
        ('gramos', 'Gramos'),
    ]
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    tipo_condimento = models.CharField(max_length=50)
    fraccion = models.CharField(max_length=20, choices= fracciones)

    def __str__(self):
        return f"{self.nombre}"
    

class Recetas(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    tipo_receta = models.CharField(max_length=50)
    complejidad = models.CharField(max_length=50)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nombre}"

mgm_app/forms.py
from django import forms
from .models import Usuarios

class UsuariosForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        fields = ['nombre', 'apellido']

mgm_app/views.py
from django.shortcuts import render
from .models import Usuarios, Condimentos, Recetas
from .forms import UsuariosForm
from django.shortcuts import render, redirect
from django.db.models import Q

# Create your views here
def inicio(request):
    busqueda = request.GET.get("Busqueda de usuarios", "")
    if busqueda:
        usuarios = Usuarios.objects.filter(
            Q(nombre__icontains=busqueda) | Q(apellido__icontains=busqueda)
        )
    else:
        usuarios = []

    return render(request, 'mgm_app/inicio.html', {
        'usuarios': usuarios,
        'busqueda': busqueda
    })

def recetas(request):
    recetas = Recetas.objects.all()
    return render(request, 'mgm_app/recetas.html', context={'recetas': recetas})


def usuario_creacion(request):
    if request.method == 'POST':
        form = UsuariosForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mgm_app:usuarios')
    else:
        form = UsuariosForm()
    
    return render(request, 'mgm_app/usuario_creacion.html', {'form': form})

def usuarios(request):
    busqueda = request.GET.get("busqueda", None)
    if busqueda:
        usuarios = Usuarios.objects.filter(nombre__icontains=busqueda)
    else:
        usuarios = Usuarios.objects.all()
    return render(request, 'mgm_app/usuarios.html', {'usuarios': usuarios})


def condimentos(request):
    condimentos = Condimentos.objects.all()
    return render(request, 'mgm_app/condimentos.html', context={'condimentos': condimentos})

mgm_app/templates/mgm_app/condimentos.html
{% extends 'mgm_app/index.html' %}

{% block title %}Inicio{% endblock title %}
{% block navbar_brand %}Mi App de Cocina{% endblock navbar_brand %}
{% block content_title %}Condimentos{% endblock content_title%}


{{% block content %}
  <h4 class="mb-3">CONDIMENTOS EXISTENTES</h4>
  <ul class="list-group mb-3">
    {% for condimento in condimentos %}
      <li class="list-group-item list-group-item-action">
        <div>
          <h5 class="mb-1">{{ condimento.nombre }}</h5>
        </div>
      </li>
    {% empty %}
      <li class="list-group-item">No hay condimentos registradas.</li>
    {% endfor %}
  </ul>
{% endblock content %}

mgm_app/templates/mgm_app/index.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mi Primera Aplicación | {% block title %}{% endblock title %}</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{% block navbar_brand %}{% endblock %}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menuNav" aria-controls="menuNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="menuNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'mgm_app:inicio' %}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mgm_app:recetas' %}">Recetas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mgm_app:condimentos' %}">Condimentos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mgm_app:usuarios' %}">Usuarios</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container mt-5">
  <h1 class="text-center mb-4">
    {% block content_title %}
    {% endblock content_title %}
  </h1>

  {% block content %}    
  {% endblock content %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

mgm_app/templates/mgm_app/inicio.html
{% extends 'mgm_app/index.html' %}

{% block title %}Inicio{% endblock title %}
{% block navbar_brand %}Mi App de Cocina{% endblock navbar_brand %}
{% block content_title %}Bienvenido a Mi App{% endblock content_title%}

{% block content %}
{% endblock content %}

mgm_app/templates/mgm_app/recetas.html
{% extends 'mgm_app/index.html' %}

{% block title %}Inicio{% endblock title %}
{% block navbar_brand %}Mi App de Cocina{% endblock navbar_brand %}
{% block content_title %}Recetas{% endblock content_title%}

{% block content %}
  <h4 class="mb-3">RECETAS EXISTENTES</h4>
  <ul class="list-group mb-3">
    {% for receta in recetas %}
      <li class="list-group-item list-group-item-action">
        <div>
          <h5 class="mb-1">{{ receta.nombre }}</h5>
        </div>
      </li>
    {% empty %}
      <li class="list-group-item">No hay recetas registradas.</li>
    {% endfor %}
  </ul>
{% endblock content %}

mgm_app/templates/mgm_app/usuario_creacion.html
{% extends 'mgm_app/index.html' %}

{% block title %}Inicio{% endblock title %}
{% block navbar_brand %}Mi App de Cocina{% endblock navbar_brand %}
{% block content_title %}Creación de nuevos Usuarios{% endblock content_title%}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Crear Usuario" class="btn btn-primary">
        <a href="{% url 'mgm_app:usuarios' %}">Cancelar</a>
    </form>

{% endblock content %}

mgm_app/templates/mgm_app/usuarios.html
{% extends 'mgm_app/index.html' %}

{% block title %}Inicio{% endblock title %}
{% block navbar_brand %}Mi App de Cocina{% endblock navbar_brand %}
{% block content_title %}Usuarios{% endblock content_title%}



{% block content %}
  <a href="{% url 'mgm_app:usuario_creacion' %}" class="btn btn-primary mb-3">Crear Usuario</a>

  <form action="{% url 'mgm_app:usuarios' %}" method="get">
    <input type="text" name="busqueda" placeholder="Buscar usuario por nombre..." type="submit"
    class="form-control mb-3">
  </form>

  <h4 class="mb-3">USUARIOS EXISTENTES</h4>
  <ul class="list-group mb-3">
    {% for usuario in usuarios %}
      <li class="list-group-item list-group-item-action">
        <div>
          <h5 class="mb-1">{{ usuario.apellido }}, {{ usuario.nombre }}</h5>
        </div>
      </li>
    {% empty %}
      <li class="list-group-item">No hay usuarios registrados.</li>
    {% endfor %}
  </ul>
{% endblock content %}